Resources:
  # Lambda function that connects the user to database
  ConnectFunction:
    Type: AWS::Lambda::Function
    Properties: 
      Code: 
        S3Bucket: chat-backend-functions
        S3Key: send-message
      Description: String
      FunctionName: String
      Handler: index.handler
      MemorySize: 2000 #128 - 3008
      ReservedConcurrentExecutions: 0 #0 - 1000
      Role:
        !GetAtt:
          - LambdaExecutionRole
          - Arn
      Runtime: nodejs12.x
      Timeout: 20 #1 - 900
      TracingConfig:
        Mode: Active

  # Permissions for the lambda functions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - execute-api:Invoke
              - execute-api:ManageConnections
            Resource: arn:aws:execute-api:*:*:*

  # Lambda functions x X
  # ApiGateway
  # Finish IAM Role
